### ISSUE TITLE
Mailing list is inaccessible

### ISSUE THREAD

**Issue by sbp** [mntmn/interim#10]
```
$ curl -Is http://sympa.mntmn.com/info/interim-dev
HTTP/1.1 502 Bad Gateway
```

**Comment by benthor** [comment]
Can confirm. Would be a shame if this project vanishes into obscurity...

**Comment by wasamasa** [comment]
Any updates on this?  An IRC channel on Freenode or alike might be a fine alternative...

**Comment by mntmn** [comment]
The mailing list is down, sorry. There wasn't a lot of traffic and the perl contraption that is sympa didn't survive a server update. Will switch to IRC for now (#interim-os on freenode). Would be cool to have a interim-powered bot.
