### ISSUE TITLE
Picture in README is almost entirely black

### ISSUE THREAD

**Issue by carstenhag** [mntmn/interim#18]
https://camo.githubusercontent.com/41e73d141e87a743980bc66d24dffde37b5251a8/687474703a2f2f64756d702e6d6e746d6e2e636f6d2f696e746572696d2d70617065722f696c6c757374726174696f6e732f696e746572696d2d706963747572652e6a7067

The image in the readme seems cut off, eg about 90% of it is just black.

**Comment by mntmn** [comment]
Strange, it was truncated by GitHub's cache layer somehow. Should be OK now?

**Comment by carstenhag** [comment]
Yeah works now, haha
