### ISSUE TITLE
rpi2-build.sh missing libuspi compilation step

### ISSUE THREAD

**Issue by tidux** [mntmn/interim#6]
Adding these lines before `$COMPILE -o build/interim-arm.elf` fixes the script.

```shell
THISDIR=$(pwd)
cd devices/rpi2/uspi/lib
make clean && make
cd ${THISDIR}
```

**Comment by mntmn** [comment]
Thanks, I integrated this just now.

**Comment by wasamasa** [comment]
You'll probably want `pushd` and `popd` instead.
